#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - name: gateway
        image: $CONTAINER_REGISTRY/gateway:$VERSION
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 4000
        env:
        - name: PORT
          value: "4000"
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
        - name: FORCE_READY_FAIL
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000